baseURL = "https://juliusreade.com/"
languageCode = "en-us"
title = "Julius Reade."
theme = "reade_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-85083093-1"

[author]
  name = "Julius Reade"

[params]
  description = "I build, deploy and maintain digital infrastructure."
