baseURL = "https://juliusreade.com/"
languageCode = "en-us"
title = "Julius Reade | I Build Digital Products"
theme = "reade_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    # post = "/guide/:slug"

[author]
  name = "Julius Reade"

[params]
  author = "Julius Reade"
  description = "Julius Reade | I Build Digital Products"
