baseURL = "https://juliusreade.com/"
languageCode = "en-us"
title = "Julius Reade."
theme = "reade_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-85083093-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    # post = "/guide/:slug"

[author]
  name = "Julius Reade"

[params]
  title = "Julius Reade."
  author = "Julius Reade"
  description = "An infrequent display of words and digital cacophony."
